src/alpaca_eval/decoders/huggingface_local.py
Hello,
I have figured a hacky way to allow showing progress while using hf pipeline. I thought it might be useful for others. Let me know what you think.
=> Add progress bar

src/alpaca_eval/analyze.py, src/alpaca_eval/annotators/pairwise_evaluator.py, src/alpaca_eval/utils.py
minor changes to simplify inheritance in `alpaca_farm`. Not sure why black did so many changes
=> [CLEAN] Simplify inheritance

setup.py, src/alpaca_eval/decoders/anthropic.py, src/alpaca_eval/utils.py
=> [ENH] upgrade anthropic 0.3

.github/workflows/update_leaderboard.yml
=> [CI] leaderboard formatting

.pre-commit-config.yaml, docs/format_export_leaderboards.py, scripts/precompute.py, src/alpaca_eval/analyze.py, src/alpaca_eval/annotators/pairwise_evaluator.py, src/alpaca_eval/completion_parsers.py, src/alpaca_eval/decoders/anthropic.py, src/alpaca_eval/decoders/cohere.py, src/alpaca_eval/decoders/huggingface_api.py, src/alpaca_eval/decoders/huggingface_local.py, src/alpaca_eval/decoders/openai.py, src/alpaca_eval/main.py, src/alpaca_eval/plotting.py, src/alpaca_eval/utils.py, tests/test_analyze.py, tests/test_completion_parsers.py, tests/test_decoders_integration.py, tests/test_decoders_unit.py, tests/test_main.py, tests/test_pairwise_evaluator.py, tests/test_utils.py
=> [CLEAN] setting up precommit

.github/workflows/set_version.py, .github/workflows/update_pypi.yml, .gitignore, tests/test_decoders_unit.py, tests/test_main.py
=> [ENH] add CI for package release

.env, .github/workflows/update_pypi.yml
pypi release has small issues (not showing on github)
=> [CI] Ci pypi 

src/alpaca_eval/annotators/__init__.py, src/alpaca_eval/annotators/base.py, src/alpaca_eval/annotators/pairwise_evaluator.py, tests/integration_tests/test_example_integration.py
base annotator will simplify inheritance in other projects (e.g. beyond pairwise or using DB instead of JSON
=> [ENH] add base annotator 

src/alpaca_eval/__init__.py, src/alpaca_eval/annotators/base.py, src/alpaca_eval/annotators/pairwise_evaluator.py, src/alpaca_eval/completion_parsers.py, src/alpaca_eval/processors.py, src/alpaca_eval/utils.py
adds `processors_to_kwargs` to easily allow pre and postprocessing of the dataframe before and after annotations
=> [ENH] adds processors

.github/workflows/set_version.py, src/alpaca_eval/__init__.py, src/alpaca_eval/annotators/base.py, src/alpaca_eval/annotators/pairwise_evaluator.py, src/alpaca_eval/processors.py
=> [STYLE] fix ill-formatted logging message

src/alpaca_eval/models_configs/openbuddy-llama-30b-v7.1/configs.yaml, src/alpaca_eval/models_configs/openbuddy-llama-65b-v8/configs.yaml
Sorry, I have made mistakes on the models' `pretty_name`.
=> Fix typo on pretty_name

src/alpaca_eval/annotators/base.py, src/alpaca_eval/processors.py
solve https://github.com/tatsu-lab/alpaca_farm/issues/61
=> [BUG] utils.DUMMY_EXAMPLE

src/alpaca_eval/decoders/openai.py
They changed the message to `Please reduce the length...`
=> Fix mssg check

src/alpaca_eval/decoders/openai.py
fixes https://github.com/tatsu-lab/alpaca_eval/issues/198
=> [BUG] fix no OAI org id set

requirements.txt, setup.py
=> [BUG] force openai >1.5.0

src/alpaca_eval/models_configs/internlm2-chat-20b-ppo/configs.yaml, src/alpaca_eval/models_configs/internlm2-chat-20b-ppo/prompt.txt
In [this PR](https://huggingface.co/internlm/internlm2-chat-20b/discussions/3), we have made adjustments to the chat template of InternLM2 chat models. The previous template was somewhat unusual, so we decided to revise it.
=> update InternLM2 chat template

src/alpaca_eval/constants.py
=> update ELO for llama-2-13b-chat-hf

src/alpaca_eval/models_configs/Samba-CoE-v0.1/configs.yaml, src/alpaca_eval/models_configs/Samba-CoE-v0.2-best-of-16/configs.yaml, src/alpaca_eval/models_configs/Samba-CoE-v0.2/configs.yaml
We achieved 300 + tokens/per second!
=> Updating link to a super fast demo!

src/alpaca_eval/models_configs/Llama-3-Instruct-8B-SimPO/configs.yaml, src/alpaca_eval/models_configs/gemma-2-9b-it-DPO/configs.yaml, src/alpaca_eval/models_configs/gemma-2-9b-it-SimPO/configs.yaml
Added links to the three following models:
- gemma-2-9b-it-DPO
- gemma-2-9b-it-SimPO
- Llama-3-Instruct-8B-SimPO
=> update model links

src/alpaca_eval/models_configs/LMCocktail-10.7B-v1/configs.yaml, src/alpaca_eval/models_configs/Llama-3-Instruct-8B-SimPO/configs.yaml, src/alpaca_eval/models_configs/Starling-LM-7B-alpha-ExPO/configs.yaml, src/alpaca_eval/models_configs/Starling-LM-7B-beta-ExPO/configs.yaml, src/alpaca_eval/models_configs/causallm-14b/configs.yaml, src/alpaca_eval/models_configs/deita-7b-v1.0/configs.yaml, src/alpaca_eval/models_configs/internlm2-chat-20b-ExPO/configs.yaml, src/alpaca_eval/models_configs/internlm2-chat-7b-ExPO/configs.yaml, src/alpaca_eval/models_configs/merlinite-7B-AOT/configs.yaml, src/alpaca_eval/models_configs/openbuddy-llama2-13b-v11.1/configs.yaml, src/alpaca_eval/models_configs/pairrm-tulu-2-13b/configs.yaml, src/alpaca_eval/models_configs/pairrm-tulu-2-70b/configs.yaml, src/alpaca_eval/models_configs/phi-2/configs.yaml, src/alpaca_eval/models_configs/tulu-2-dpo-13b-ExPO/configs.yaml, src/alpaca_eval/models_configs/tulu-2-dpo-13b/configs.yaml, src/alpaca_eval/models_configs/tulu-2-dpo-70b-ExPO/configs.yaml, src/alpaca_eval/models_configs/tulu-2-dpo-70b/configs.yaml, src/alpaca_eval/models_configs/tulu-2-dpo-7b-ExPO/configs.yaml, src/alpaca_eval/models_configs/tulu-2-dpo-7b/configs.yaml, src/alpaca_eval/models_configs/zephyr-7b-alpha-ExPO/configs.yaml, src/alpaca_eval/models_configs/zephyr-7b-beta-ExPO/configs.yaml
=> [BUG] backward compatibility vllm do_sample -> use_beam_search

src/alpaca_eval/evaluators_configs/alpaca_eval_vllm_llama3_70b_fn/alpaca_eval_fn.txt, src/alpaca_eval/evaluators_configs/alpaca_eval_vllm_llama3_70b_fn/configs.yaml
=> [ENH] add example for LLama 3 vllm

src/alpaca_eval/models_configs/gemma-2-9b-it-WPO-HB/configs.yaml
Thank you for including our models! I realized that I missed adding the link to the model. Could you please update the commit with the model link? We would greatly appreciate it.
=> Add link to gemma-2-9b-it-WPO-HB

src/alpaca_eval/decoders/openai.py, src/alpaca_eval/evaluators_configs/alpaca_eval_cot_gpt4_turbo_fn/configs.yaml, src/alpaca_eval/evaluators_configs/alpaca_eval_gpt4_fn/configs.yaml, src/alpaca_eval/evaluators_configs/alpaca_eval_gpt4_turbo_fn/configs.yaml, src/alpaca_eval/evaluators_configs/chatgpt_fn/configs.yaml
- function calls outside of tools or depreciated in OpenAI.
- ChatML is now the default for all new models => make it default
=> [ENH] OpenAI use tools instead of functions

src/alpaca_eval/models_configs/Llama-3-8B-Instruct-SkillMix/configs.yaml
Only updated the links for Llama-3-8B-Instruct-SkillMix
=> Updated HF Link in model_configs for Llama-3-8B-Instruct-SkillMix
